/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MyDatabase": import("@cloudflare/workers-types").D1Database
    "MyWeb": {
      "type": "sst.cloudflare.ReactRouter"
      "url": string
    }
  }
}

import "sst"
export {}